name: dnsmasq-escoand
version: 2.79test1snap1
summary: Dnsmasq provides network infrastructure for small networks
description: |
  DNS, DHCP, router advertisement and network boot. It is designed
  to be lightweight and have a small footprint, suitable for resource
  constrained routers and firewalls
icon: icon.png

grade: devel
confinement: strict

apps:
  dnsmasq:
    command: dnsmasq -k -7 $SNAP_DATA/,*.conf -x $SNAP_COMMON/dnsmasq.pid --user= --group=
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

parts:
  dnsmasq:
    plugin: make
    source: git://thekelleys.org.uk/dnsmasq.git
    source-tag: v2.79test1
    organize:
      usr/local/sbin/dnsmasq: bin/dnsmasq
    prime:
      - bin/dnsmasq
