name: dnsmasq-escoand
version: 2.76snap2
summary: Dnsmasq provides network infrastructure for small networks
description: |
  DNS, DHCP, router advertisement and network boot. It is designed
  to be lightweight and have a small footprint, suitable for resource
  constrained routers and firewalls

grade: devel
confinement: devmode

apps:
  dnsmasq:
    command: dnsmasq -D $SNAP_DATA/dnsmasq.conf -x $SNAP_DATA/dnsmasq.pid
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]

parts:
  dnsmasq:
    plugin: make
    source: https://github.com/lool/dnsmasq.git
    source-tag: v2.76
    organize:
      usr/local/sbin/dnsmasq: bin/dnsmasq
    snap:
      - bin/dnsmasq
