name: dnsmasq-escoand
version: 2.76snap5
summary: Dnsmasq provides network infrastructure for small networks
description: |
  DNS, DHCP, router advertisement and network boot. It is designed
  to be lightweight and have a small footprint, suitable for resource
  constrained routers and firewalls

grade: stable
confinement: strict

apps:
  dnsmasq:
    command: dnsmasq -7 $SNAP_DATA/,*.conf -x $SNAP_COMMON/dnsmasq.pid
    daemon: forking
    restart-condition: always
    plugs: [network, network-bind]

parts:
  dnsmasq:
    plugin: make
    source: https://github.com/lool/dnsmasq.git
    source-tag: v2.76
    organize:
      usr/local/sbin/dnsmasq: bin/dnsmasq
    prime:
      - bin/dnsmasq
